### ISSUE TITLE
why using a -500 buffer on landsat filtering ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/fcdm#1]
In the script when the `masking_2` method is applied (Masking Step 2: Masking of sensor errors and non-forest areas) you sometime use a negative buffer of -500 on the image geometry (like in [L947](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L947)) and sometime you don't (like in [L1957]((https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L1957)).

From what I understand this is a difference between landsat and sentinel sensor but can you explain me why ?

**Comment by Andi1974** [comment]
Yes, you are right ... it is because of Landsat data sometimes have artifacts close to the image borders (not all bands provide sound values). S2 does not have this problematic (as far as I know) ... maybe due to the tiling.
