### ISSUE TITLE
capping_fires is never called 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/fcdm#2]
In the script ([L848](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L848)) you created a function `capping_fires`that is never called. Can you explain what was its purpose and tell me if I can safely remove it ?

**Comment by Andi1974** [comment]
That was originally planned in a different way and was not implemented. You can safely remove.
