### ISSUE TITLE
change the event date display 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/fcdm#26]
In the current implementation the dates are stored in the following format: YYYYMMDD as pure integer. 
It's convinient to human read this information but not very convenient for display as dates will rapidly be split appart. 

In BFAST and CUSUM we use instead the following : 
YYYY.year_fraction which is way much easier to interpret on a QGIS map. 

example: 
20120613 become 2012.51

What do you think ?

**Comment by Andi1974** [comment]
Dear Pierrick,

sorry, I did not follow that ...
Fine for me the way you propose.

Ciao, Andi

Am Do., 15. Juli 2021 um 11:03 Uhr schrieb Rambaud Pierrick <
***@***.***>:
