### ISSUE TITLE
Is it possible to merge S2 images with the others ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/fcdm#3]
In your script the S2 data are only treated from [L1934](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L1934) and have a slightly different data preparation process. 

Is it formally impossible to merge it with the other satellites ? (maybe by adding some normalization steps)

**Comment by Andi1974** [comment]
Up to now I concentrated on my new S1 approach ... however, the question you raised was also in my mind (but never had time for that) ... so it would be interesting to go along that direction as well!
