### ISSUE TITLE
what should be displayed to the end user ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/fcdm#4]
In your code every `second` or `base` map is displayed (so for the landsat family option, it's 5*2 maps) but with visibility set to false. 

The only one that are always displayed are the final 
- `NBR_difference_capped`
- `NBR_Imagecollection_second_normalized_min` (`yearday` and `NBR` bands) [L2049](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L2049)
- `NBR_Imagecollection_base_normalized_min` (`yearday` and `NBR` bands) [L2004](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L2004)

On javascript side, a map with visiblity to false is in fact not requested from the server. It's not the same with the `geemap` lib (that provide the binding beween `ipyleaflet`and the GEE API).

How much relevant are the extra map ? 
Can I decide to only display and/or download the 5 main one ?

**Comment by Andi1974** [comment]
Yes, only the visible ones are the most important.
