### ISSUE TITLE
module 'ee' has no attribute 'Credentials'

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/fcdm#45]
when downloading an image

**Comment by 12rambau** [comment]
I had completely forgot about this one. FYTK it's a legacy member of `ee`. as you have updated its version by upgrading sepal_ui in the requirements it's not available any more. The new way to access the credential is the pattern we use in sepal_ui here: https://github.com/12rambau/sepal_ui/blob/5277a82db3fe4e5bb971eb6676b28d9652b90564/sepal_ui/scripts/decorator.py#L40

**Comment by dfguerrerom** [comment]
thanks @12rambau, I, however, have updated the class with the method we are using in our GDrive class, https://github.com/12rambau/sepal_ui/pull/539/commits/592d6600dd49ce93e833587e6f95a48e5d834bcf. 

closed with a2237db33ed68f344921a2bd70d55b2b4f5588a6
