### ISSUE TITLE
when to apply the landsat_7 improvement ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/fcdm#5]
starting from [L1152](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L1152) the landsat 7 receive a specific patch using the `improve_threshold` parameter.

This improvement is not applyed when dealing with the landsat family in [L1667](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L1667) is it normal ? 

If yes then why applying it when the selected collections are `L7`, `L78`, `L57` ?

**Comment by Andi1974** [comment]
These are two different approaches how to derive the Delta-rNBR. From line 1529 it is the 'inter sensor' approach, while the others are the single sensor or intra-sensor approaches. Maybe this could be best discussed in our online meeting. 
And to cut a long story short ... here I implemented it like this up to now but it would make sense to at least check how the results look like implementing the improve_sensor option to that as well ...
