### ISSUE TITLE
do we cap after or before the merge ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/fcdm#6]
When you use the landsat family you have 2 different behaviours : 
- [L1863](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L1863) you cap the nbr collection for each collection `if index == 'change'`
- [L1913](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L1913) here for ìndex == 'NBR'`you cap after the merge.

Any specific reason for these two different behaviors ?

**Comment by Andi1974** [comment]
Similar to above comment: only work on the script if 'index' is set to 'change' and leave aside all if statements where 'index' is set to 'NBR'.
