### ISSUE TITLE
can I use the roadless map ?

### ISSUE THREAD

**Issue by 12rambau** [12rambau/fcdm#7]
The roadless map asset is available under the name : "users/ClassifLandsat072015/Roadless36y/AnnualChange_1982_2018" 
I tested it in the code editor of EE and the asset is actually not public as specified [L912](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L912). 

So the question is simple, can I use it ?

**Comment by Andi1974** [comment]
No, not that one as it is old. However, there should be (already?!) or at least very soon the full map publicly available. So, we can then simply replace this link by the then actual one.

**Comment by 12rambau** [comment]
I will then disable the option until the map is available but code the behavior anyway
