### ISSUE TITLE
cap give a binary map ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/fcdm#8]
I f I read the code [L845](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L845) I have the feeling the the output map is a binary map -1, 0 because you multiply the result of the where by -1. 

But according to the comment : 
"Capping at 0 and -1 (positive values are set to 0; values <= -1 are set to -1" 

Who should I trust ?

**Comment by Andi1974** [comment]
No, the output is not binary. That statement leaves the range between 0 and -1 with its original values but caps the upper and lower borders. The multiplication with -1 simply inverses the values (in this constellation the values of interest are negative). Thus, this multiplication with -1 allows to continue working with positive numbers.
