### ISSUE TITLE
when should I use the kernel adjustment ? 

### ISSUE THREAD

**Issue by 12rambau** [12rambau/fcdm#9]
The kernel_adjustment method is used a lot in the code but I cannot really understand when it's necessary. Several configuration exists : 

- in the first dataset combos "LXX" with Ìndex == 'change'`(like [L990](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L990)) you systematically adapt the kernel for base and second nbr collections. 
- in the first dataset combos "LXX" with Ìndex == 'NBR'`(like [L1035](https://github.com/12rambau/fcdm/blob/e7075483d2fe5969beceea8a776cc2cb8357941f/copy_gee_script.js#L1035)) you just cap the collection without kernel adaptation. 

would it change anything to the end result if I adapt the kernel for everyone ? (even if there is no comparaison between 2 collections) 

> my objective is to optimise the writting of the functions and I try to remove as many if as I can

**Comment by Andi1974** [comment]
Within the (optical-based) FCDM tool there are two possibilities implemented to screen for changes:
1) Delta-rNBR (with the self-referencing step using the kernel) for screening for small-scale degradation (e.g. selective logging) events (this one you are interested in)
2) Delta-NBR (without the self-referencing step using the kernel) for screening for large-scale impacts such as fire scars, etc.. (this one does not belong to the actual Delta-rNBR approach)
For your translation work you have to consider only point 1, meaning you only have to use the script if the variable 'Index' is set to 'Change'.
